### ISSUE TITLE
ObjC compiled code is failing in Xcode7-beta5

### ISSUE THREAD

**Issue by boazin** [khawars/KSTokenView#18] opened 2015-08-18 09:08 UTC
Lots of errors, can't wrap my head around them.
Same errors are caused when trying to build ObjCExample.

If you don't mind taking a quick look into it. Thanks!

**Comment by khawars** [comment] 2015-08-18 12:50
@boazin which errors occur? Please explain in more detail with development environment.

**Comment by boazin** [comment] 2015-08-18 13:12
Well. I installed the latest xcode-beta iOS9 on my MAC, (xcode7-beta5) and tried `ObjCExample` project (after mine failed - I checked if yours if failing as well)

There are a lot of compilation errors (copying from log is the best I can provide):

```
/Users/boazin/KSTokenView/KSTokenView/KSTokenView.swift:351:13: error: a non-failable initializer cannot chain to failable initializer 'init(coder:)' written with 'init?'
      super.init(coder: aDecoder)
            ^
/Users/boazin/KSTokenView/KSTokenView/KSTokenView.swift:351:13: note: force potentially-failing result with '!'
      super.init(coder: aDecoder)
            ^
                !
/Users/boazin/KSTokenView/KSTokenView/KSTokenView.swift:350:13: note: propagate the failure with 'init?'
   required init(coder aDecoder: NSCoder) {
            ^
                ?
/Users/boazin/KSTokenView/KSTokenView/KSTokenView.swift:369:39: error: could not find member 'FlexibleWidth'
      _tokenField.autoresizingMask = .FlexibleWidth | .FlexibleHeight
                                     ~^~~~~~~~~~~~~
/Users/boazin/KSTokenView/KSTokenView/KSTokenView.swift:402:31: error: extraneous argument label 'shouldUpdateText:' in call
      _tokenField.updateLayout(shouldUpdateText: false)
                              ^~~~~~~~~~~~~~~~~~~
                               
/Users/boazin/KSTokenView/KSTokenView/KSTokenView.swift:486:39: error: value of optional type 'String?' not unwrapped; did you mean to use '!' or '?'?
         addTokenWithTitle(tokenField.text)
                                      ^
                                          !
/Users/boazin/KSTokenView/KSTokenView/KSTokenView.swift:764:17: error: 'sorted' is unavailable: call the 'sort()' method on the collection
         return sorted(filteredResults, { s1, s2 in return self._sortStringForObject(s1) < self._sortStringForObject(s2) })
                ^~~~~~
Swift.sorted:1:87: note: 'sorted' has been explicitly marked unavailable here
@available(*, unavailable, message="call the 'sort()' method on the collection") func sorted<C : SequenceType>(source: C, _ isOrderedBefore: (C.Generator.Element, C.Generator.Element) -> Bool) -> [C.Generator.Element]
                                                                                      ^
/Users/boazin/KSTokenView/KSTokenView/KSTokenView.swift:827:40: error: invalid use of '()' to call a value of non-function type '[NSLayoutConstraint]'
               for index in 0 ... self.constraints().count-1 {
                                       ^          ~~
                                                  
/Users/boazin/KSTokenView/KSTokenView/KSTokenView.swift:876:30: error: value of optional type 'String?' not unwrapped; did you mean to use '!' or '?'?
         let first: String = olderText.substringToIndex(advance(olderText.startIndex, range.location)) as String
                             ^
                                      !
/Users/boazin/KSTokenView/KSTokenView/KSTokenView.swift:876:65: error: value of optional type 'String?' not unwrapped; did you mean to use '!' or '?'?
         let first: String = olderText.substringToIndex(advance(olderText.startIndex, range.location)) as String
                                                                ^
                                                                         !
/Users/boazin/KSTokenView/KSTokenView/KSTokenView.swift:877:31: error: value of optional type 'String?' not unwrapped; did you mean to use '!' or '?'?
         let second: String = olderText.substringFromIndex(advance(olderText.startIndex, range.location+1)) as String
                              ^
                                       !
/Users/boazin/KSTokenView/KSTokenView/KSTokenView.swift:877:68: error: value of optional type 'String?' not unwrapped; did you mean to use '!' or '?'?
         let second: String = olderText.substringFromIndex(advance(olderText.startIndex, range.location+1)) as String
                                                                   ^
                                                                            !
/Users/boazin/KSTokenView/KSTokenView/KSTokenView.swift:881:84: error: value of optional type 'String?' not unwrapped; did you mean to use '!' or '?'?
         if (contains(tokenizingCharacters, string) && olderText != KSTextEmpty && olderText.stringByTrimmingCharactersInSet(NSCharacterSet.whitespaceCharacterSet()) != "") {
                                                                                   ^
                                                                                            !
/Users/boazin/KSTokenView/KSTokenView/KSTokenView.swift:882:31: error: value of optional type 'String?' not unwrapped; did you mean to use '!' or '?'?
            addTokenWithTitle(olderText, tokenObject: nil)
                              ^
                                       !
/Users/boazin/KSTokenView/KSTokenView/KSTokenView.swift:885:25: error: value of optional type 'String?' not unwrapped; did you mean to use '!' or '?'?
         searchString = olderText+string
                        ^
                                 !
/Users/boazin/KSTokenView/KSTokenView/KSTokenView.swift:889:11: error: type 'String' does not conform to protocol 'CollectionType'
      if (count(searchString) >= minimumCharactersToSearch && searchString != "\n") {
          ^
/Users/boazin/KSTokenView/KSTokenView/KSTokenView.swift:943:74: error: downcast from 'UITableViewCell?' to 'UITableViewCell' only unwraps optionals; did you mean to use '!'?
      cell = tableView.dequeueReusableCellWithIdentifier(cellIdentifier) as? UITableViewCell
             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ ^   ~~~~~~~~~~~~~~~
```

**Comment by khawars** [comment] 2015-08-18 17:21
@boazin Xcode 7 contains Swift 2. Currently KSTokenView is not compatible with Swift 2. I'll soon download Xcode 7 and will make it compatible.

**Comment by boazin** [comment] 2015-08-18 17:24
Thank you. We started preparing for iOS9 so I'm guessing it is something
inevitable...

**Comment by boazin** [comment] 2015-08-23 09:33
Hey, any news? something I can assist with?

**Comment by khawars** [comment] 2015-08-28 08:24
@boazin I was super busy in last few days. The issue is fixed now. Please check latest commit fb08c27352764533334a8715e3a509b155be8007.
You can reopen the issue if it still exists.

**Closed by khawars** 2015-08-28 08:24 UTC

**Comment by boazin** [comment] 2015-08-28 11:21
Thanks man! I even tried to learn swift with my busy schedule in order to pitch in and not be a burden... 
(and clearly haven't made it yet)

Anyways - I still have 2 compilation errors (in ObjCExample project)

/Users/boazin/KSTokenView/KSTokenView/KSTokenView.swift:351:13: A non-failable initializer cannot chain to failable initializer 'init(coder:)' written with 'init?'
/Users/boazin/KSTokenView/KSTokenView/KSTokenField.swift:140:13: A non-failable initializer cannot chain to failable initializer 'init(coder:)' written with 'init?'

Thanks.

**Comment by boazin** [comment] 2015-08-31 14:05
Just to update you - I tried it with the new xcode7 beta6 - some different errors, got stuck on `Command failed due to signal: Segmentation fault: 11`

I'm guessing we will wait to the GM version and then dive into the problems together...

**Comment by senfi** [comment] 2015-09-11 06:48
This issue is still present at GM in the Xcode 7-non-beta. 
Seems like something in ```func tokenFieldShouldChangeHeight(height: CGFloat)``` in KSTokenView.swift.
If i put everything in this func into ```/* */``` and just return, the compiler compiles.

**Comment by orfdna** [comment] 2015-09-20 14:39
Same thing happened to me - Thank you senfi for the tip, as I can now progress on to debug iOS 9.

khawars, we would appreciate any help on this.

Thanks.
